=== thekingcommander/projectWebxV2/multiLivre-SpringWS/src/main/resources/multi-livre.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="https://example.com/webx/multi-livre" targetNamespace="https://example.com/webx/multi-livre"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Response" type="tns:ResponseType" />
	<xs:complexType name="ResponseType">
		<xs:choice>
			<xs:element name="error" type="tns:ErrorType" />
			<xs:element name="result" type="tns:ResultType" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="ErrorType">
		<!-- the name of the REST API that failed and its HTTP status code -->
		<xs:attribute name="api" type="xs:string" />
		<xs:attribute name="status" type="xs:int" />
	</xs:complexType>
	<xs:complexType name="ResultType">
		<xs:sequence>
			<xs:element name="titre" type="xs:string" />
			<xs:element name="auteur" type="tns:AuteurType" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="bibliotheque" type="tns:BibliothequeType"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AuteurType">
		<xs:all>
			<xs:element name="prenom" type="xs:string" />
			<xs:element name="nom" type="xs:string" />
		</xs:all>
	</xs:complexType>
	<xs:complexType name="BibliothequeType">
		<xs:all>
			<xs:element name="nom" type="xs:string" />
			<xs:element name="distance" type="xs:double" />
		</xs:all>
	</xs:complexType>
	<xs:element name="Request" type="tns:RequestType" />
	<xs:complexType name="RequestType">
		<xs:sequence>
			<xs:element name="doi" type="xs:string" />
			<xs:element name="adresse" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== thekingcommander/projectWebxV2/multiLivre-SpringWS/src/main/resources/ResponseType.xml
<Response xmlns="https://example.com/webx/multi-livre" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://example.com/webx/multi-livre multi-livre.xsd">
<result>
<titre>Interactive Theorem Proving and Program Development</titre>
<auteur>
<nom>Brezis</nom>
<prenom>Haim</prenom>
</auteur>
<bibliotheque>
<nom>NICE-Bibl.Mathématiques</nom>
<distance>5.8496503829956055</distance>
</bibliotheque>
<bibliotheque>
<nom>BREST-Télécom Bretagne</nom>
<distance>7.64534854888916</distance>
</bibliotheque>
<bibliotheque>
<nom>TOULOUSE3-Bib Math. et Méca.</nom>
<distance>0.05459066852927208</distance>
</bibliotheque>
<bibliotheque>
<nom>TOULOUSE-ISAE</nom>
<distance>0.06854286789894104</distance>
</bibliotheque>
<bibliotheque>
<nom>BORDEAUX-UB-Bib.BMI</nom>
<distance>2.344137668609619</distance>
</bibliotheque>
<bibliotheque>
<nom>MONTPELLIER-BU Sciences</nom>
<distance>2.443669319152832</distance>
</bibliotheque>
<bibliotheque>
<nom>RENNES-INSA</nom>
<distance>5.454003810882568</distance>
</bibliotheque>
<bibliotheque>
<nom>TOURS-Bib. Maths Physique Theor.</nom>
<distance>3.8148717880249023</distance>
</bibliotheque>
<bibliotheque>
<nom>GRENOBLE-Inst.Fourier</nom>
<distance>4.635854244232178</distance>
</bibliotheque>
<bibliotheque>
<nom>ORLEANS-MAPMO</nom>
<distance>4.274799346923828</distance>
</bibliotheque>
<bibliotheque>
<nom>NANCY-UL-BU RECH. MAT.</nom>
<distance>6.936525344848633</distance>
</bibliotheque>
<bibliotheque>
<nom>METZ-UL-BU METZ MOSELLE</nom>
<distance>7.278217315673828</distance>
</bibliotheque>
<bibliotheque>
<nom>LILLE1-UFR Maths pures &amp; appliq.</nom>
<distance>7.229050159454346</distance>
</bibliotheque>
<bibliotheque>
<nom>CLERMONT FD2-Mathématiques</nom>
<distance>2.7432498931884766</distance>
</bibliotheque>
<bibliotheque>
<nom>PAU-Bibliothèque de l'IPRA</nom>
<distance>43.62684631347656</distance>
</bibliotheque>
<bibliotheque>
<nom>LYON1-BU.Sciences</nom>
<distance>4.083254814147949</distance>
</bibliotheque>
<bibliotheque>
<nom>LYON1-BU Sciences Mathématique</nom>
<distance>4.079982757568359</distance>
</bibliotheque>
<bibliotheque>
<nom>LYON-BDL-Sciences</nom>
<distance>4.0185065269470215</distance>
</bibliotheque>
<bibliotheque>
<nom>PARIS6-BUPMC-Math Info Recherche</nom>
<distance>5.324301242828369</distance>
</bibliotheque>
<bibliotheque>
<nom>PARIS6-BUPMC-Bibli des licences</nom>
<distance>5.326671123504639</distance>
</bibliotheque>
</result>
</Response>
